name: PR Debug
on: [ pull_request ]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR #${{ github.event.pull_request.number }} triggered at ${{ github.event.pull_request.head.ref }}"
